# This workflow will build and push a node.js application to an Azure Web App on every push to the master branch.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: bclausingwb-api            # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './wwwroot'        # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'                     # set this to the dotnet version to use
  BUILD_CONFIG: 'Release'                       # set this to the build configuration { Release | Debug }
  PROJECT_PATH: './WebService/WebService.csproj'  # set this to the path to the project to be deployed (avoid deploying test project)

jobs:
  build-and-deploy:
    name: Build, Test and Deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build
      run: dotnet build --configuration ${{ env.BUILD_CONFIG }}
    - name: Test
      run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIG }}
    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} --no-build --configuration ${{ env.BUILD_CONFIG }} --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
